config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as:'portfolio_show'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end
 
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies, dependent: :destroy
    accepts_nested_attributes_for :technologies,
    reject_if: lambda {|attr| attr['name'].blank?}
    
  include Placeholder
   validates_presence_of :title, :body, :main_image, :thumb_image
   
   def self.angular
     where(subtitle: 'Angular')
   end
    
    scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }
    
    after_initialize :set_defaults
    
    def set_defaults
      self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
      self.thumb_image ||= Placeholder.image_generator(height: '300', width: '200')
    end
    
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout 'portfolio'
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
  
  def index
    @portfolio_items = Portfolio.all
    @page_title = "Portfolios"
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end
  

  def new
    @portfolio_item = Portfolio.new
    3.times {@portfolio_item.technologies.build }
  end


  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  
  def edit
    @portfolio_item = Portfolio.find(params[:id])
    @page_title = "Edit"
  end
  
  def update
    @portfolio_item = Portfolio.find(params[:id])
    
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
    
  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    #perform the lookup
    @portfolio_item = Portfolio.find(params[:id])
    
    #destroy/delete the record
    @portfolio_item.destroy
    
    #Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Record was removed.' }
    end
  end
  
  
  private
  
  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      technologies_attributes: [:name]
                                      )
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <div class='row'>
    <div class='col-md-6'>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div> 
      
      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>
    </div>
  
  <div class= 'col-md-6'>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control' %>
    </div>
    <hr>
    <h2> Technologies Used</h2>
  
    <div class= 'form group'>
      <%= f.fields_for :technologies do |technology_form| %>
      <li>
       <%= technology_form.label :name %>
       <%= technology_form.text_field :name, class: 'form-control' %>
      </li>
      <% end %>
    </div>
  </div>

  <div class= "form-group">
    <%= f.submit 'Save Portfolio', class: 'btn btn-primary btn-block'%>
    
    
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
          <div class="card">
            <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
            <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item), class: 'portfolio-title' %></p>
            <p class="card-text"><%= portfolio_item.subtitle %></p>
            <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
            <%= link_to "Delete Portfolio Item", portfolio_path(portfolio_item), method: :delete, data: {confirm: 'Are you sure?'} if logged_in?(:site_admin) %>
          </div>

app/views/portfolios/angular.html.erb
<h1>angular portfolio items</h1>

<%= link_to "Create new item", new_portfolio_url %>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) if logged_in?(:site_admin) %>
  <%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class='container portfolio_form'>

<h1>Edit this Portfolio Item</h1>

<%= render "form", portfolio_item: @portfolio_item%>

</div>

app/views/portfolios/index.html.erb
<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

    <div class="album text-muted">
      <div class="container">
        <div class="row">
          
        <%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1>Create a New Portfolio Item</h1>

<%= render "form", portfolio_item: @portfolio_item%>

app/views/portfolios/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-7'>
      <%= image_tag @portfolio_item.main_image %>
    </div>
    
    <div class='col-md-5'>
      <h1><%= @portfolio_item.title %></h1>
        <hr>
      <em><%= @portfolio_item.subtitle %></em>
      <p><%= @portfolio_item.body %></p>
        <hr>
      <h2>Technologies Used</h2>
        <% @portfolio_item.technologies.each do |t| %>
        <p><%= t.name %></p>
        <% end %>
        <hr>
        <%= link_to 'View All Portfolio Items', portfolios_path %>
    </div>
  </div>
</div>